apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::959199095557:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::959199095557:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RMQK9FDCPA44
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-08T21:04:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1140"
  uid: 94c6e126-21a0-4d81-8a8e-a22ea6b40f7f
